version: "3.3"

services:
  faker_app:
    build: .
    container_name: faker_app
    volumes:
      - .:/code
    expose:
      - "8083"
    env_file:
      - envs/local/web/web.env
    networks:
      - nginx_network
    command: python manage.py runserver 0.0.0.0:8083
    depends_on:
      - db

  db:
    image: postgres:15.1-bullseye
    container_name: db
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/
    env_file:
      - envs/local/db/db.env
    expose:
      - "5432"
    networks:
      - nginx_network
    command: ["postgres", "-c", "log_statement=all"]

networks:
  nginx_network:
    external: true

volumes:
  postgres_db_data:
